name: fix_map
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_cupertino_localizations: ^1.0.1
  equatable: ^0.6.1
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  intl: ^0.15.8
  shared_preferences: 0.5.3+3
  permission_handler: ^4.0.0
  fluttertoast: ^3.1.3
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+11
  geolocator: ^5.1.5
  dio: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map/